### ISSUE TITLE
Fix ParFlow GPU build errors

### ISSUE THREAD

**Issue by kvrigor** [HPSCTerrSys/TSMP2#63]
`--ParFlowGPU` has been introduced in #53 and isn't working yet. Fix will be done on another PR.

```bash
$ ./build_tsmp2.sh --ParFlowGPU --no_update --compiler gnu --clean_first
[ 41%] Building CUDA object pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o
In file included from /p/software/jurecadc/stages/2025/software/CUDA/12/targets/x86_64-linux/include/cub/detail/nvtx3.hpp:635,
from /p/software/jurecadc/stages/2025/software/CUDA/12/targets/x86_64-linux/include/cub/detail/nvtx.cuh:49,
from /p/software/jurecadc/stages/2025/software/CUDA/12/targets/x86_64-linux/include/cub/device/device_adjacent_difference.cuh:41,
from /p/software/jurecadc/stages/2025/software/CUDA/12/targets/x86_64-linux/include/cub/cub.cuh:62,
from /home/TSMP2/models/parflow/pfsimulator/parflow_lib/pf_cudaloops.h:35,
from /home/TSMP2/models/parflow/pfsimulator/parflow_lib/backend_mapping.h:61,
from /home/TSMP2/models/parflow/pfsimulator/parflow_lib/parflow.h:81,
from /home/TSMP2/models/parflow/pfsimulator/parflow_lib/axpy.c:32,
from /home/TSMP2/models/parflow/pfsimulator/parflow_lib/axpy.cpp:22:
/p/software/jurecadc/stages/2025/software/CUDA/12/targets/x86_64-linux/include/nvtx3/nvToolsExt.h:179:2: error: #error "Trying to #include NVTX version 3 in a source file where an older NVTX version has already been included.  If you are not directly using NVTX (the NVIDIA Tools Extension library), you are getting this error because libraries you are using have included different versions of NVTX.  Suggested solutions are: (1) reorder #includes so the newest NVTX version is included first, (2) avoid using the conflicting libraries in the same .c/.cpp file, or (3) update the library using the older NVTX version to use the newer version instead."
179 | #error "Trying to #include NVTX version 3 in a source file where an older NVTX version has already been included.  If you are not directly using NVTX (the NVIDIA Tools Extension library), you are getting this error because libraries you are using have included different versions of NVTX.  Suggested solutions are: (1) reorder #includes so the newest NVTX version is included first, (2) avoid using the conflicting libraries in the same .c/.cpp file, or (3) update the library using the older NVTX version to use the newer version instead."
|  ^~~~~
gmake[5]: *** [pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/build.make:107: pfsimulator/parflow_lib/CMakeFiles/pfsimulator.dir/axpy.cpp.o] Error 1
```

https://github.com/parflow/parflow/pull/575 might possibly fix this.

**Comment by kvrigor** [comment]
@AGonzalezNicolas unfortunately this wouldn't be included in #53 since the error caused by the newer nVidia compilers in `Stages/2025` which has no easy workaround.
